[package]
name = "o1"
version = "0.6.5"
description = "O(1) complexity, minimum allocations and concurrency friendly collection of data structures and algorithms"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[dependencies]
rayon = { version = "1.0" }

[dev-dependencies]
rand = "0.5"
